#!/usr/bin/env node
/**
 * Proof runner — `npm run proofs`.
 *
 * Executes the committed machine proofs against the REAL sources (no copies
 * of app logic live in this directory). Committed to the repo as of v6.8:
 * the historical validation suite (v62-equivalence-prover + liquid
 * baselines, the 1,182-check harness, flip-test.ts, the v5x/v6x sims) lived
 * in session-scoped tmp scratchpads and was wiped with them — twice. This
 * directory is the durable replacement; add future proofs HERE, never to
 * tmp.
 *
 * Shim recipe (why .generated/ exists): app/models/settings.server.ts
 * line 1 imports prisma from ../db.server (Prisma client). The proof needs
 * none of the DB functions, node --experimental-strip-types cannot resolve
 * the extensionless relative import, and no tsx/ts-node is installed. So
 * this runner regenerates .generated/settings.server.shim.ts from the real
 * module on EVERY run — byte-identical except line 1, which becomes an
 * inert stub. If the real file's first line ever changes, the runner fails
 * loudly instead of proving against a stale copy.
 *
 * Steps:
 *   1. v68-settings-derivation-proof.ts  (node --experimental-strip-types)
 *   2. v68-az-split-sim.cjs              (plain node, vm-extracts the real
 *                                         cellexia-pdp.js az stock module)
 */
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..", "..");
const realPath = path.join(root, "app", "models", "settings.server.ts");
const genDir = path.join(here, ".generated");
const shimPath = path.join(genDir, "settings.server.shim.ts");

const PRISMA_IMPORT = 'import prisma from "../db.server";\n';
const real = fs.readFileSync(realPath, "utf8");
if (!real.startsWith(PRISMA_IMPORT)) {
  console.error(
    "run-proofs: app/models/settings.server.ts no longer starts with the " +
      "expected prisma import — update the shim recipe in " +
      "scripts/proofs/run-proofs.mjs before trusting any proof result.",
  );
  process.exit(1);
}
const shim =
  "// GENERATED by scripts/proofs/run-proofs.mjs — do not edit. Byte-identical\n" +
  "// to app/models/settings.server.ts except this prisma-import replacement.\n" +
  "const prisma = {} as any;\n" +
  real.slice(PRISMA_IMPORT.length);
fs.mkdirSync(genDir, { recursive: true });
fs.writeFileSync(shimPath, shim);

const steps = [
  [
    "v6.8 settings-derivation + 31-key flip proof",
    [
      "--experimental-strip-types",
      "--no-warnings=ExperimentalWarning",
      path.join(here, "v68-settings-derivation-proof.ts"),
    ],
  ],
  ["v6.8 az stock/ships split sim", [path.join(here, "v68-az-split-sim.cjs")]],
];

let failed = 0;
for (const [label, args] of steps) {
  console.log(`\n== ${label} ==`);
  try {
    execFileSync(process.execPath, args, { stdio: "inherit", cwd: root });
  } catch {
    failed++;
    console.error(`run-proofs: FAILED — ${label}`);
  }
}
if (failed > 0) {
  console.error(`\nrun-proofs: ${failed}/${steps.length} proof step(s) FAILED`);
  process.exit(1);
}
console.log(`\nrun-proofs: all ${steps.length} proof steps PASSED`);
